### ISSUE TITLE
Maybe contribute the metrics to tslearn?

### ISSUE THREAD

**Issue by MaxBenChrist** [lukauskas/dtwco#5]
Having worked with time series and dtw, I would love to see a dedicated fast dtw implementation.

You could also consider to contribute the code to tslearn (https://github.com/rtavenar/tslearn), they seem to have some dtw in their metric submodule

**Comment by lukauskas** [comment]
I'll have a look at this, but I have two concerns already:

1. There is a licensing conflict as `tslearn` is BSD 2-clause, whereas this is GPL3 because `mlpy` code was GPL3.
2. Ironically, I personally do not use DTW for time series analysis. I use it for [genomic](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-016-1306-0), proteomic and image data instead, so I often shy away from placing it in a time-series oriented environment.

**Comment by lukauskas** [comment]
Also as of a few months ago `tslearn` contains Sakoe Chiba and Itakura. Okay I need to look into this further.

**Comment by lukauskas** [comment]
https://tslearn.readthedocs.io/en/stable/user_guide/dtw.html?highlight=sakoe%20chiba#additional-constraints

Somebody else has implemented these to `tslearn`. It is indeed a better home there.
Meanwhile I am retiring this repository.
